### PR TITLE
[WIP] Added docs for contracts

### PR DESCRIPTION
**Pull request by usmanmuhd**
I am currently working on adding docs for the Smart Contracts.
Solves issue #34

### CODE REVIEW

**Comment by gakonst** [comment]
Hi @usmanmuhd thank you for taking the issue. 

This issue was actually opened in June and since then our codebase has changed a lot and is much more documented, compared to how it was at the time (https://github.com/loomnetwork/plasma-cash/tree/5a12e3744f1e63670945617cc69b54890290a419). 

As a result, I believe there is not much to further add regarding code comments, however if you believe there are more places to add documentation to clean things up and make it easier to bootstrap for a developer, happy to accept more commits in this PR. (I guess you'll add some more docs in the near future?)

**Comment by usmanmuhd** [comment]
Hey @gakonst 
Going by the issue, I can see that the contracts are not according to the natspec directives, python comments are also not in line with the docs strings and so on. So I think I can set it right and make it in line with the accepted specifications.

**Comment by gakonst** [comment]
Sure go ahead then

**Comment by vs77bb** [comment]
Hi @usmanmuhd could you update us on your progress here? Hope you're doing well!

**Comment by usmanmuhd** [comment]
@vs77bb I will be pushing a few changes in a day or two.

**Pull request closed without merging**
